### ISSUE TITLE
Can't authenticate with amazon.com (cookie)

### ISSUE THREAD

**Issue by jerryamile** [tonesto7/echo-speaks#337]
When I go through the initial steps to get the cookie added to the smart things (classic) app after doing the Heroku steps.
I can't get logged in (get error messsage from amazon) with amazon.com or even to try to add  the cookie manually without login to amazon.com doesn't work either for me. Using https://github.com/tonesto7/echo-speaks/issues/92 (Cloudedturtle) method. The smart thiings app saids I didn't login with amazon yet.

I just redid all the installation steps for smart things, this time using ST-Community-Installer, still same thing the amazon login page leads me to nowhere, (Looking for Something? page) before it was invalid email or user.

So to me it seems, that
The amazon website for alexa (login) seems to be having some type of problem: https://echo-speaks-(mypersonalinfo).herokuapp.com/proxy this redirects to: https://www.amazon.com/ap/signin

Here is a alexa login page, this URL works but doesn't help in adding the cookie to the smart things Echo Speaks:
https://www.amazon.com/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Fecho.amazon.com%2F&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&

Is this just me or are others experiencing this problem? Makes me wonder.

Thank you, this been going on a few days now.
I'm thinking amazon changed something......

![IMG-3546](https://user-images.githubusercontent.com/29029886/87104369-acfc0f00-c225-11ea-93fc-75ceca7af938.PNG)
![IMG-3545](https://user-images.githubusercontent.com/29029886/87104370-ad94a580-c225-11ea-9482-58fac59d2b63.PNG)
![IMG-3544](https://user-images.githubusercontent.com/29029886/87104371-ad94a580-c225-11ea-9eb4-224030425109.PNG)
![unnamed](https://user-images.githubusercontent.com/29029886/87193014-c6ed2e80-c2c5-11ea-8480-97e4b0c6a1a5.jpg)
![unnamed (1)](https://user-images.githubusercontent.com/29029886/87193026-cb194c00-c2c5-11ea-83e1-840609902025.jpg)

**Comment by cradixus** [comment]
I'm here for similar reasons.  I'm new to Echo Speaks.  I just installed via the Community Installer.  I believe I did everything correctly, but when I try to login, I get an error from Amazon that essentially means that Echo Speaks took me to an incorrect URL.  So, I like your observation that it appears as though "Amazon changed something".

**Comment by richcj10** [comment]
same problem :(

**Comment by jerryamile** [comment]
Yes it does richcj10, 
I found a thread on samsung smart things community after posting here,
Looks like others are in the same boat:
https://community.smartthings.com/t/release-echo-speaks-v3-actions/173073/894

**Comment by cesarnovo1971** [comment]
Me too... Exactly the same problem...

**Comment by tonesto7** [comment]
I just pushed out a new server update that will address this issue.  I'm also preparing to push out some fixes to the app and devices sometime today

**Comment by richcj10** [comment]
Sweet! Tha ks for your hard work.
Can I ask what the issue was?

**Comment by jerryamile** [comment]
> I just pushed out a new server update that will address this issue. I'm also preparing to push out some fixes to the app and devices sometime today

Awesome, thank you so much, working well on my end now! Able to authenticate now with Amazon, Great work/much appreciated! I’ll close the request now  🙏

**Comment by Toggz** [comment]
Im still unable to login in the UK. Not retrieving cookie, thus no authorisation approval. If using the. com domain cookie, it is approved but app is not recognising. Co.uk domain login, there is no change. Guess v3.6.3.0 will fix? Thank you!

**Comment by ibruceuk78** [comment]
I'm still having an issue signing in.  It gets the Cookie retrieved successfully page but then goes back to the "Goto Login Page" again and again no matter how many times it try.  

I have updated the app, handlers and server.

**Comment by Jmarcos13** [comment]
> I'm still having an issue signing in. It gets the Cookie retrieved successfully page but then goes back to the "Goto Login Page" again and again no matter how many times it try.
> 
> I have updated the app, handlers and server.

Same as you!! It keeps looping me. I tried the manual cookie as described in the issue #92, but it didn't worked. 
Waiting for news 😄
